'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react'; import { useParams } from 'next/navigation'; import Link from 'next/link';
import { useCart } from '@/components/CartProvider'; import { createClient } from '@/lib/supabase/browser'; import { dict, isLocale } from '@/lib/i18n'; import { turkeyProvinces } from '@/lib/turkey';

type Settings={standard_shipping_price:number;free_shipping_min_quantity:number|null;pickup_enabled:boolean;pickup_title_ar:string;pickup_title_en:string;pickup_title_tr:string;pickup_description_ar:string;pickup_description_en:string;pickup_description_tr:string;bank_instructions_ar:string;bank_instructions_en:string;bank_instructions_tr:string};
export default function Checkout(){const params=useParams<{locale:string}>();const locale=isLocale(params.locale)?params.locale:'tr';const t=dict[locale];const cart=useCart();const supabase=useMemo(()=>createClient(),[]);const [settings,setSettings]=useState<Settings|null>(null);const [shippingMethod,setShippingMethod]=useState<'standard'|'pickup'>('standard');const [discount,setDiscount]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [order,setOrder]=useState<any>(null);
useEffect(()=>{supabase.from('store_settings').select('*').single().then(({data})=>setSettings(data as Settings));},[supabase]);
const shipping=shippingMethod==='pickup'?0:(settings?.free_shipping_min_quantity&&cart.count>=settings.free_shipping_min_quantity?0:Number(settings?.standard_shipping_price||0));
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!cart.items.length)return;setLoading(true);setError('');const form=new FormData(e.currentTarget);const customer={firstName:form.get('firstName'),lastName:form.get('lastName'),email:form.get('email'),phone:form.get('phone'),province:form.get('province'),district:form.get('district'),address:form.get('address'),addressDetails:form.get('addressDetails'),postalCode:form.get('postalCode')};const {data,error}=await supabase.rpc('create_store_order',{p_customer:customer,p_items:cart.items.map(i=>({variantId:i.variantId,quantity:i.quantity})),p_discount_code:discount||null,p_shipping_method:shippingMethod,p_locale:locale});if(error){setError(error.message);setLoading(false);return;}setOrder(data);cart.clear();setLoading(false);}
if(order){const bank=settings?.[`bank_instructions_${locale}` as keyof Settings]||settings?.bank_instructions_en;return <main className="section page narrow"><div className="success-card"><p className="eyebrow">DUTHUR</p><h1>{t.orderConfirmed}</h1><p>{t.orderNumber}: <strong>#{order.orderNumber}</strong></p><div className="totals"><div><span>{t.subtotal}</span><b>{Number(order.subtotal).toFixed(2)} TL</b></div><div><span>{t.discount}</span><b>-{Number(order.discount).toFixed(2)} TL</b></div><div><span>{t.shipping}</span><b>{Number(order.shipping).toFixed(2)} TL</b></div><div className="grand"><span>{t.total}</span><b>{Number(order.total).toFixed(2)} TL</b></div></div><h3>{t.bankTransfer}</h3><p>{String(bank||'')}</p><Link href={`/${locale}/products`} className="primary inline">{t.continueShopping}</Link></div></main>}
return <main className="checkout-page"><form onSubmit={submit} className="checkout-form"><h1>{t.checkoutTitle}</h1><h2>{t.contactTitle}</h2><div className="grid2"><input required type="email" name="email" placeholder={t.email}/><input required name="phone" placeholder={t.phone}/></div><h2>{t.delivery}</h2><div className="fixed-country">Türkiye</div><div className="grid2"><input required name="firstName" placeholder={t.firstName}/><input required name="lastName" placeholder={t.lastName}/></div><div className="grid2"><select required name="province" defaultValue=""><option value="" disabled>{t.province}</option>{turkeyProvinces.map(p=><option key={p}>{p}</option>)}</select><input required name="district" placeholder={t.district}/></div><input required name="address" placeholder={t.address}/><input name="addressDetails" placeholder={t.addressDetails}/><input name="postalCode" placeholder={t.postalCode}/><h2>{t.shippingMethod}</h2><label className="choice"><input type="radio" checked={shippingMethod==='standard'} onChange={()=>setShippingMethod('standard')}/><span>{t.standardShipping}</span><b>{shipping===0?'FREE':`${settings?.standard_shipping_price||0} TL`}</b></label>{settings?.pickup_enabled&&<label className="choice"><input type="radio" checked={shippingMethod==='pickup'} onChange={()=>setShippingMethod('pickup')}/><span>{settings[`pickup_title_${locale}` as keyof Settings] as string||t.pickup}<small>{settings[`pickup_description_${locale}` as keyof Settings] as string}</small></span><b>FREE</b></label>}<div className="discount-row"><input value={discount} onChange={e=>setDiscount(e.target.value.toUpperCase())} placeholder={t.discountCode}/></div>{error&&<p className="form-error">{error}</p>}<button className="primary" disabled={loading||!cart.items.length}>{loading?'...':t.placeOrder}</button></form><aside className="checkout-summary"><h2>{t.yourCart}</h2>{cart.items.map(i=><div className="summary-item" key={i.variantId}><span>{i.title} × {i.quantity}<small>{Object.values(i.optionValues).join(' / ')}</small></span><b>{(i.price*i.quantity).toFixed(2)} TL</b></div>)}<div className="totals"><div><span>{t.subtotal}</span><b>{cart.subtotal.toFixed(2)} TL</b></div><div><span>{t.shipping}</span><b>{shipping===0?'FREE':`${shipping.toFixed(2)} TL`}</b></div><div className="grand"><span>{t.total}</span><b>{(cart.subtotal+shipping).toFixed(2)} TL*</b></div></div><small>* {locale==='ar'?'يتم التحقق النهائي من السعر وكود الخصم والمخزون عند تأكيد الطلب.':'Final price, discount and stock are verified when the order is submitted.'}</small></aside></main>}
